### PR TITLE
Really Rewrote WP_Object_Cache implementation

### PR DESCRIPTION
**Pull request by msigley**
Reopening this because I screwed up the last PR.

Unfortunately I had intended to just remove just the preload feature to fix the scaling issue but that feature was masking other issues and this turned into a whole rewrite using the existing work as a reference.

In my testing this version is more reliable and just as fast as with the preloading due to the PHP cache array optimizations. I am using a locally hosted version of redis however and the preloading optimization may be targeted to address network latency.

### CODE REVIEW

**Comment by soulseekah** [comment]
Yes, we'll need to do some benchmarking. 
You don't appear to be using `mget`, that's where our implementation shined. Preloading all the cache keys. You're loading one key at a time again it seems, defeating the whole purpose of the implementation. I'd say your implementation is no different from Eric Mann's one then, the original.

**Comment by msigley** [comment]
I am aware I am missing the preloading feature. We could work on adding it back it but the existing implementation was built on top of logic issues and I saw no way around unraveling it.

The only benefit of the preloading feature is greatly eliminating network latency by reducing the number of Redis calls in certain Redis setups where the Redis instance is on a separate server. Again the PHP cache array implementation eliminates duplicate get calls which helps this issue. This feature would mostly be for things like Amazon ElastiCache but Redis is supposed to be so fast this shouldn't matter. 
It has downsides that out weigh its usefulness in my opinion such as introducing a logN scaling issue in the size of the cache in RAM, completely ignoring key expiration, inflating the size of PHP's RAM use by loading a bunch of keys that may not even be required (not every request to the same URL is the same).

I think there are other optimizations that could be made to greater benefit. For example we try eliminating the 'alloptions' cache key with a Redis::keys('options:*') passed into a Redis::mget() call. Done correctly this would eliminate the notorious 'alloptions' bug and reduce the size of the cached data.

**Comment by soulseekah** [comment]
Thanks for the explanation. Our benchmarks were run locally and yielded the following results:

image

2ms vs 20ms. This is with a local redis running and 500+ keys on a vanilla WordPress page.

The screenshot above is from https://pressjitsu.com/blog/redis-object-cache-wordpress/

You speak of logic errors etc. it's absolutely fine to provide fixes for them but:

1. In their own PRs
2. With tests as first commits and fixes as second commits
3. Detailed explanation on each error

This is a preload implementation. You seem to be removing the preload part so we're back to square one - the original Eric Mann implementation. Our plugin exists solely for the preload version.

Regarding RAM usage, sure but you have to have like a billions of keys. If there's a way to limit the preload to most popularly used or something - that would be a nice feature.

You seem to have run into some specific setup where you have a lot of data. This resulted in a cascade of commits that we're having a hard time estimating and understanding. So let's just open up new issues and PRs and discuss each separate thing on its own.

We appreciate the hard work you're putting in. But we need benchmarks and tests.

**Review by soulseekah — COMMENTED** [review]
I'm confused. We already have this, it was inherited from Eric Mann's implementation.

**Comment by soulseekah** [comment]
#14 #15 #16 #17 have been created instead.

**Pull request closed without merging**
